/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrioritiesRouteImport } from './routes/priorities'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as PrioritiesIndexRouteImport } from './routes/priorities/index'
import { Route as TasksCreateRouteImport } from './routes/tasks/create'
import { Route as TasksTaskIdRouteImport } from './routes/tasks/$taskId'
import { Route as PrioritiesCreateRouteImport } from './routes/priorities/create'
import { Route as PrioritiesPriorityIdRouteImport } from './routes/priorities/$priorityId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrioritiesRoute = PrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const PrioritiesIndexRoute = PrioritiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrioritiesRoute,
} as any)
const TasksCreateRoute = TasksCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TasksRoute,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)
const PrioritiesCreateRoute = PrioritiesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => PrioritiesRoute,
} as any)
const PrioritiesPriorityIdRoute = PrioritiesPriorityIdRouteImport.update({
  id: '/$priorityId',
  path: '/$priorityId',
  getParentRoute: () => PrioritiesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/priorities': typeof PrioritiesRouteWithChildren
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRouteWithChildren
  '/priorities/$priorityId': typeof PrioritiesPriorityIdRoute
  '/priorities/create': typeof PrioritiesCreateRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/create': typeof TasksCreateRoute
  '/priorities/': typeof PrioritiesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/priorities/$priorityId': typeof PrioritiesPriorityIdRoute
  '/priorities/create': typeof PrioritiesCreateRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/create': typeof TasksCreateRoute
  '/priorities': typeof PrioritiesIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/priorities': typeof PrioritiesRouteWithChildren
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRouteWithChildren
  '/priorities/$priorityId': typeof PrioritiesPriorityIdRoute
  '/priorities/create': typeof PrioritiesCreateRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/create': typeof TasksCreateRoute
  '/priorities/': typeof PrioritiesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/priorities'
    | '/signup'
    | '/tasks'
    | '/priorities/$priorityId'
    | '/priorities/create'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/priorities/'
    | '/tasks/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/priorities/$priorityId'
    | '/priorities/create'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/priorities'
    | '/tasks'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/priorities'
    | '/signup'
    | '/tasks'
    | '/priorities/$priorityId'
    | '/priorities/create'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/priorities/'
    | '/tasks/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PrioritiesRoute: typeof PrioritiesRouteWithChildren
  SignupRoute: typeof SignupRoute
  TasksRoute: typeof TasksRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priorities': {
      id: '/priorities'
      path: '/priorities'
      fullPath: '/priorities'
      preLoaderRoute: typeof PrioritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/priorities/': {
      id: '/priorities/'
      path: '/'
      fullPath: '/priorities/'
      preLoaderRoute: typeof PrioritiesIndexRouteImport
      parentRoute: typeof PrioritiesRoute
    }
    '/tasks/create': {
      id: '/tasks/create'
      path: '/create'
      fullPath: '/tasks/create'
      preLoaderRoute: typeof TasksCreateRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/priorities/create': {
      id: '/priorities/create'
      path: '/create'
      fullPath: '/priorities/create'
      preLoaderRoute: typeof PrioritiesCreateRouteImport
      parentRoute: typeof PrioritiesRoute
    }
    '/priorities/$priorityId': {
      id: '/priorities/$priorityId'
      path: '/$priorityId'
      fullPath: '/priorities/$priorityId'
      preLoaderRoute: typeof PrioritiesPriorityIdRouteImport
      parentRoute: typeof PrioritiesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PrioritiesRouteChildren {
  PrioritiesPriorityIdRoute: typeof PrioritiesPriorityIdRoute
  PrioritiesCreateRoute: typeof PrioritiesCreateRoute
  PrioritiesIndexRoute: typeof PrioritiesIndexRoute
}

const PrioritiesRouteChildren: PrioritiesRouteChildren = {
  PrioritiesPriorityIdRoute: PrioritiesPriorityIdRoute,
  PrioritiesCreateRoute: PrioritiesCreateRoute,
  PrioritiesIndexRoute: PrioritiesIndexRoute,
}

const PrioritiesRouteWithChildren = PrioritiesRoute._addFileChildren(
  PrioritiesRouteChildren,
)

interface TasksRouteChildren {
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksCreateRoute: typeof TasksCreateRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksCreateRoute: TasksCreateRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PrioritiesRoute: PrioritiesRouteWithChildren,
  SignupRoute: SignupRoute,
  TasksRoute: TasksRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
