/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CommitmentsRouteImport } from './routes/commitments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as CommitmentsIndexRouteImport } from './routes/commitments/index'
import { Route as TasksCreateRouteImport } from './routes/tasks/create'
import { Route as TasksTaskIdRouteImport } from './routes/tasks/$taskId'
import { Route as CommitmentsCreateRouteImport } from './routes/commitments/create'
import { Route as CommitmentsCommitmentIdRouteImport } from './routes/commitments/$commitmentId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitmentsRoute = CommitmentsRouteImport.update({
  id: '/commitments',
  path: '/commitments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const CommitmentsIndexRoute = CommitmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommitmentsRoute,
} as any)
const TasksCreateRoute = TasksCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TasksRoute,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)
const CommitmentsCreateRoute = CommitmentsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => CommitmentsRoute,
} as any)
const CommitmentsCommitmentIdRoute = CommitmentsCommitmentIdRouteImport.update({
  id: '/$commitmentId',
  path: '/$commitmentId',
  getParentRoute: () => CommitmentsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commitments': typeof CommitmentsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRouteWithChildren
  '/commitments/$commitmentId': typeof CommitmentsCommitmentIdRoute
  '/commitments/create': typeof CommitmentsCreateRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/create': typeof TasksCreateRoute
  '/commitments/': typeof CommitmentsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/commitments/$commitmentId': typeof CommitmentsCommitmentIdRoute
  '/commitments/create': typeof CommitmentsCreateRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/create': typeof TasksCreateRoute
  '/commitments': typeof CommitmentsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commitments': typeof CommitmentsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRouteWithChildren
  '/commitments/$commitmentId': typeof CommitmentsCommitmentIdRoute
  '/commitments/create': typeof CommitmentsCreateRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/create': typeof TasksCreateRoute
  '/commitments/': typeof CommitmentsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commitments'
    | '/login'
    | '/signup'
    | '/tasks'
    | '/commitments/$commitmentId'
    | '/commitments/create'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/commitments/'
    | '/tasks/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/commitments/$commitmentId'
    | '/commitments/create'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/commitments'
    | '/tasks'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/commitments'
    | '/login'
    | '/signup'
    | '/tasks'
    | '/commitments/$commitmentId'
    | '/commitments/create'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/commitments/'
    | '/tasks/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommitmentsRoute: typeof CommitmentsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TasksRoute: typeof TasksRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commitments': {
      id: '/commitments'
      path: '/commitments'
      fullPath: '/commitments'
      preLoaderRoute: typeof CommitmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/commitments/': {
      id: '/commitments/'
      path: '/'
      fullPath: '/commitments/'
      preLoaderRoute: typeof CommitmentsIndexRouteImport
      parentRoute: typeof CommitmentsRoute
    }
    '/tasks/create': {
      id: '/tasks/create'
      path: '/create'
      fullPath: '/tasks/create'
      preLoaderRoute: typeof TasksCreateRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/commitments/create': {
      id: '/commitments/create'
      path: '/create'
      fullPath: '/commitments/create'
      preLoaderRoute: typeof CommitmentsCreateRouteImport
      parentRoute: typeof CommitmentsRoute
    }
    '/commitments/$commitmentId': {
      id: '/commitments/$commitmentId'
      path: '/$commitmentId'
      fullPath: '/commitments/$commitmentId'
      preLoaderRoute: typeof CommitmentsCommitmentIdRouteImport
      parentRoute: typeof CommitmentsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CommitmentsRouteChildren {
  CommitmentsCommitmentIdRoute: typeof CommitmentsCommitmentIdRoute
  CommitmentsCreateRoute: typeof CommitmentsCreateRoute
  CommitmentsIndexRoute: typeof CommitmentsIndexRoute
}

const CommitmentsRouteChildren: CommitmentsRouteChildren = {
  CommitmentsCommitmentIdRoute: CommitmentsCommitmentIdRoute,
  CommitmentsCreateRoute: CommitmentsCreateRoute,
  CommitmentsIndexRoute: CommitmentsIndexRoute,
}

const CommitmentsRouteWithChildren = CommitmentsRoute._addFileChildren(
  CommitmentsRouteChildren,
)

interface TasksRouteChildren {
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksCreateRoute: typeof TasksCreateRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksCreateRoute: TasksCreateRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommitmentsRoute: CommitmentsRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TasksRoute: TasksRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
